### PR TITLE
Haskellbook ch06

### PR DESCRIPTION
**Pull request by sid-mercury**
I'm still working on Ch6 I am about halfway through.  I'm wondering a bit about read and show, and Serialization was mentioned briefly and then not discussed. I'm guessing there must be some kind of JSON mechanism / library

Also found it interesting that Show has multiple methods, but we only implemented one as that is the MINIMAL.  I'm guessing this is a common thing in Haskell as well but that seems a little odd to me, it's kind of like having interfaces with optional methods.

### CODE REVIEW

**Comment by sid-mercury** [comment]
Oops, I branched off ch05 so I have those commits in here as well. The new file is https://github.com/sid-mercury/haskellbook/pull/4/files#diff-95533ffe72ea23b54c63c405035caa50c25b40f23cee0a94445a4c1d09e27263 (ch06/chex.hs)

**Comment by friedbrice** [comment]
> Oops, I branched off ch05

No worries :-)

**Comment by friedbrice** [comment]
> it's kind of like having interfaces with optional methods

It's more like having interfaces with _default_ methods.

Take a look at the source code. https://hackage.haskell.org/package/base-4.17.0.0/docs/src/GHC.Show.html#Show

What you will see if you read it is that `showsPrec` has a default implementation that's written in terms of `show`, so if you provide `show`, then you'll get the default impl of `showsPrec`.

**Comment by friedbrice** [comment]
> and Serialization was mentioned briefly and then not discussed

`Show` and `Read` provide quick-and-dirty serialization and de-serialization of native Haskell data.

**Pull request merged**
